server:
  port: 8080

spring:
  application:
    name: "products"

  datasource:
    url: jdbc:mysql://localhost:3306/simpleshop_product
    username: root
    password:

  jpa:
    databasePlatform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true

logging:
  level:
    com:
      simpleshop:
        product: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

products:
  message: "Welcome to SimpleShop products related docker APIs "
  contactDetails:
    name: "Marcin Seweryn - Developer"
    email: "marcinsewerynn@gmail.com"
  onCallSupport:
    - +48 123456789
    - (555) 523-1345