server:
  port: 8080

spring:
  application:
    name: "products"

  datasource:
    url: "{cipher}1415e2b3aff56a60c35bd347b3358ba0e52c7297946dbd7d87a09d90304e625e8fdab3575362848c8f0499957dcbcbeda04ff662e6bdacd41aa867bb8b4ee91d"
    username: root
    password:

  jpa:
    databasePlatform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

logging:
  level:
    com:
      simpleshop:
        product: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

products:
  message: "Welcome to SimpleShop products related docker APIs "
  contactDetails:
    name: "Marcin Seweryn - Developer"
    email: "marsew97@wp.pl"
  onCallSupport:
    - +48 123456789
    - +48 987654321